@startuml Demo

skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor transparent
skinparam NoteBackgroundColor #eee
skinparam activity {
    'FontName Ubuntu
    FontName Roboto
}

component test
component test2

@enduml
